version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i -g aws-cdk newman
      - mkdir build
      - 'curl --location --request GET "https://api.getpostman.com/collections/141384-a44305f1-37cd-44bc-ba3d-721bf6b1b634" --header "X-Api-Key: $POSTMANAPIKEY" -o _testing/Todos.postman_collection.json'
  build:
    commands:
      - cp cdk/config.example.ts cdk/config.ts
      - sed "s/environment\:\ \"Dev\"/environment\:\ \"Testing\"/" cdk/config.example.ts > cdk/config.ts
      - chmod +x cicd-deploy.sh
      - ./cicd-deploy.sh
      - newman run _testing/Todos.postman_collection.json -e _testing/Testing.postman_environment.json
      - npm run citest
  post_build:
    commands:
      - chmod +x cicd-destroy.sh
      - ./cicd-destroy.sh
